"""empty message

Revision ID: 0e1d1657b500
Revises:
Create Date: 2025-02-14 16:31:55.909541

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0e1d1657b500"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lab_manager", schema=None) as batch_op:
        op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 
                FROM pg_type 
                WHERE typname = 'labmanagertypeenum'
            ) THEN
                CREATE TYPE labmanagertypeenum AS ENUM (
                    'PI',
                    'CO_PI',
                    'LAB_MANAGER',
                    'POST_DOC',
                    'GRAD_STUDENT'
                );
            END IF;
        END$$;
        """)
        batch_op.add_column(
            sa.Column(
                "manager_type",
                sa.Enum(
                    "PI",
                    "CO_PI",
                    "LAB_MANAGER",
                    "POST_DOC",
                    "GRAD_STUDENT",
                    name="labmanagertypeenum",
                ),
                nullable=False,
                server_default="LAB_MANAGER",
            )
        )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("pronouns", sa.String(length=25), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("pronouns")

    with op.batch_alter_table("lab_manager", schema=None) as batch_op:
        batch_op.drop_column("manager_type")

    # ### end Alembic commands ###
