"""Initial migration.

Revision ID: 55928fddcb12
Revises:
Create Date: 2024-09-24 16:26:33.004366

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "55928fddcb12"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "class_years",
        sa.Column("class_year", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("class_year"),
    )
    op.create_table(
        "courses",
        sa.Column("code", sa.String(length=8), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "majors",
        sa.Column("code", sa.String(length=4), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "opportunities",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("recommended_experience", sa.String(length=500), nullable=True),
        sa.Column("pay", sa.Float(), nullable=True),
        sa.Column("one_credit", sa.Boolean(), nullable=True),
        sa.Column("two_credits", sa.Boolean(), nullable=True),
        sa.Column("three_credits", sa.Boolean(), nullable=True),
        sa.Column("four_credits", sa.Boolean(), nullable=True),
        sa.Column(
            "semester",
            sa.Enum("SPRING", "FALL", "SUMMER", name="semesterenum"),
            nullable=True,
        ),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("application_due", sa.Date(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.Column(
            "location",
            sa.Enum(
                "TBD",
                "AMOS_EATON",
                "CARNEGIE",
                "CBIS",
                "CCI",
                "CII",
                "COGSWELL",
                "DCC",
                "EMPAC",
                "GREENE",
                "JEC",
                "JROWL",
                "LALLY",
                "LINAC",
                "MRC",
                "PITTSBURGH",
                "RICKETTS",
                "SAGE",
                "VCC",
                "WALKER",
                "WEST",
                "WINSLOW",
                "REMOTE",
                name="locationenum",
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rpi_schools",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "recommends_class_years",
        sa.Column("opportunity_id", sa.Integer(), nullable=False),
        sa.Column("class_year", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["class_year"], ["class_years.class_year"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"], ["opportunities.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("opportunity_id", "class_year"),
    )
    op.create_table(
        "recommends_courses",
        sa.Column("opportunity_id", sa.Integer(), nullable=False),
        sa.Column("course_code", sa.String(length=8), nullable=False),
        sa.ForeignKeyConstraint(["course_code"], ["courses.code"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["opportunity_id"], ["opportunities.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("opportunity_id", "course_code"),
    )
    op.create_table(
        "recommends_majors",
        sa.Column("opportunity_id", sa.Integer(), nullable=False),
        sa.Column("major_code", sa.String(length=4), nullable=False),
        sa.ForeignKeyConstraint(["major_code"], ["majors.code"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["opportunity_id"], ["opportunities.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("opportunity_id", "major_code"),
    )
    op.create_table(
        "rpi_departments",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("school_id", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["rpi_schools.name"],
        ),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "lab_manager",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("department_id", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["rpi_departments.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "leads",
        sa.Column("lab_manager_id", sa.Integer(), nullable=False),
        sa.Column("opportunity_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["lab_manager_id"], ["lab_manager.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"], ["opportunities.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("lab_manager_id", "opportunity_id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.String(length=9), nullable=False),
        sa.Column("email", sa.String(length=150), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("last_name", sa.String(length=200), nullable=False),
        sa.Column("preferred_name", sa.String(length=50), nullable=True),
        sa.Column("phone_number", sa.String(length=15), nullable=True),
        sa.Column("website", sa.String(length=512), nullable=True),
        sa.Column("class_year", sa.Integer(), nullable=True),
        sa.Column("lab_manager_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["class_year"],
            ["class_years.class_year"],
        ),
        sa.ForeignKeyConstraint(
            ["lab_manager_id"],
            ["lab_manager.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "management_permissions",
        sa.Column("user_id", sa.String(length=9), nullable=False),
        sa.Column("super_admin", sa.Boolean(), nullable=False),
        sa.Column("admin", sa.Boolean(), nullable=False),
        sa.Column("moderator", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "participates",
        sa.Column("user_id", sa.String(length=9), nullable=False),
        sa.Column("opportunity_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "opportunity_id"),
    )
    op.create_table(
        "user_courses",
        sa.Column("user_id", sa.String(length=9), nullable=False),
        sa.Column("course_code", sa.String(length=8), nullable=False),
        sa.Column("in_progress", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_code"],
            ["courses.code"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "course_code"),
    )
    op.create_table(
        "user_departments",
        sa.Column("user_id", sa.String(length=9), nullable=False),
        sa.Column("department_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["rpi_departments.name"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "department_id"),
    )
    op.create_table(
        "user_majors",
        sa.Column("user_id", sa.String(length=9), nullable=False),
        sa.Column("major_code", sa.String(length=4), nullable=False),
        sa.ForeignKeyConstraint(
            ["major_code"],
            ["majors.code"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "major_code"),
    )
    op.create_table(
        "user_saved_opportunities",
        sa.Column("user_id", sa.String(length=9), nullable=False),
        sa.Column("opportunity_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "opportunity_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_saved_opportunities")
    op.drop_table("user_majors")
    op.drop_table("user_departments")
    op.drop_table("user_courses")
    op.drop_table("participates")
    op.drop_table("management_permissions")
    op.drop_table("user")
    op.drop_table("leads")
    op.drop_table("lab_manager")
    op.drop_table("rpi_departments")
    op.drop_table("recommends_majors")
    op.drop_table("recommends_courses")
    op.drop_table("recommends_class_years")
    op.drop_table("rpi_schools")
    op.drop_table("opportunities")
    op.drop_table("majors")
    op.drop_table("courses")
    op.drop_table("class_years")
    # ### end Alembic commands ###
