"""empty message

Revision ID: c72f39e93d72
Revises: 4dd3611b273e
Create Date: 2024-10-15 17:29:11.568986

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c72f39e93d72"
down_revision = "4dd3611b273e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rpi_departments", schema=None) as batch_op:
        batch_op.add_column(sa.Column("website", sa.String(length=2000), nullable=True))

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    with op.batch_alter_table("rpi_departments", schema=None) as batch_op:
        batch_op.drop_column("website")

    # ### end Alembic commands ###
