"""empty message

Revision ID: f7518ca21f44
Revises: c72f39e93d72
Create Date: 2024-10-16 01:35:20.577378

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "f7518ca21f44"
down_revision = "c72f39e93d72"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    # ### end Alembic commands ###
