name: Ruff Lint Check

on:
  pull_request:
    paths:
      - "**.py"

permissions:
  contents: read

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: astral-sh/ruff-action@c6bea5606c33b5d04902374392d9233464b90660
