name: Ruff Lint Check

on:
  pull_request:
    paths:
      - "**.py"

permissions:
  contents: read

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - uses: astral-sh/ruff-action@57714a7c8a2e59f32539362ba31877a1957dded1
